//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutenticacionPersonalizada.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolMenu
    {
        public int IdRol { get; set; }
        public int IdMenu { get; set; }
        public int Orden { get; set; }
    
        public virtual Menu Menu { get; set; }
        public virtual Rol Rol { get; set; }
    }
}
